// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbCuM3xMtK0taleHrCYqMgIkd8XI4IBP0',
    appId: '1:693078248086:ios:b465d821131d5f74a290b7',
    messagingSenderId: '693078248086',
    projectId: 'minimal-social-app-fae36',
    storageBucket: 'minimal-social-app-fae36.firebasestorage.app',
    iosBundleId: 'com.example.minimalSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbCuM3xMtK0taleHrCYqMgIkd8XI4IBP0',
    appId: '1:693078248086:ios:b465d821131d5f74a290b7',
    messagingSenderId: '693078248086',
    projectId: 'minimal-social-app-fae36',
    storageBucket: 'minimal-social-app-fae36.firebasestorage.app',
    iosBundleId: 'com.example.minimalSocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvEkOrkeKth3sRY5nfu21jflC_-c40Uwc',
    appId: '1:693078248086:web:62db6e9b12ce1bb3a290b7',
    messagingSenderId: '693078248086',
    projectId: 'minimal-social-app-fae36',
    authDomain: 'minimal-social-app-fae36.firebaseapp.com',
    storageBucket: 'minimal-social-app-fae36.firebasestorage.app',
    measurementId: 'G-H6MVHYDT4V',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvEkOrkeKth3sRY5nfu21jflC_-c40Uwc',
    appId: '1:693078248086:web:62db6e9b12ce1bb3a290b7',
    messagingSenderId: '693078248086',
    projectId: 'minimal-social-app-fae36',
    authDomain: 'minimal-social-app-fae36.firebaseapp.com',
    storageBucket: 'minimal-social-app-fae36.firebasestorage.app',
    measurementId: 'G-H6MVHYDT4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABHctUQuf6PB7eQ_3JiejPE44A3EVqGUM',
    appId: '1:693078248086:android:29c229c0a79b63fca290b7',
    messagingSenderId: '693078248086',
    projectId: 'minimal-social-app-fae36',
    storageBucket: 'minimal-social-app-fae36.firebasestorage.app',
  );

}